CREATE TABLE "persona" (
  "id" uuid PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "second_name" varchar(50),
  "last_name1" varchar(50) NOT NULL,
  "last_name2" varchar(50),
  "date_of_birth" date NOT NULL,
  "id_lugar_nacimiento" uuid NOT NULL,
  "height" numeric NOT NULL,
  "sex" sex_enum NOT NULL,
  "education_level" education_level_enum NOT NULL,
  "military_situation" military_situation_enum,
  "dni" varchar UNIQUE,
  "dni_status" dni_status_enum NOT NULL DEFAULT 'no_aplica',
  "marital_status" marital_status_enum NOT NULL,
  "occupation" varchar,
  "ethnic_group" ethnic_group_enum NOT NULL,
  CHECK ((height > 0)),
  CHECK ((sex = 'F' AND military_situation = 'no_aplica' OR sex = 'M')),
  CONSTRAINT "chk_persona_first_name_no_vacio" CHECK (trim(first_name) <> ''),
  CONSTRAINT "chk_persona_last_name1_no_vacio" CHECK (trim(last_name1) <> ''),
  CONSTRAINT "chk_persona_second_name_no_vacio_si_existe" CHECK ((second_name IS NULL OR trim(second_name) <> '')),
  CONSTRAINT "chk_persona_last_name2_no_vacio_si_existe" CHECK ((last_name2 IS NULL OR trim(last_name2) <> ''))
);